#! /bin/sh
PATH=$PATH:/usr/local/bin:$HOME/local/bin;

# load alias definitions
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# use colors for grep
export GREP_OPTIONS='--color=auto'

# make sure colors show up in iTerm
export CLICOLOR=1
export LSCOLORS=dxfxcxdxbxegedabagacad
export TERM=xterm-256color

# MacPorts Installer addition on 2011-07-25_at_23:54:05: adding an appropriate PATH variable for use with MacPorts.
# export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

# This loads RVM into a shell session.
# [[ -s "/Users/Edo/.rvm/scripts/rvm" ]] && source "/Users/Edo/.rvm/scripts/rvm"

############
# Git Stuff
############

# tell git to use macvim as the default editor
export GIT_EDITOR='/Applications/MacVim.app/Contents/MacOS/Vim -gf '

# Set the prompt for interactive shells
# http://en.tldp.org/HOWTO/Bash-Prompt-HOWTO/
if [ "$PS1" ]; then
    export PS1='>\[\e[1;31m\]\W\[\e[1;33m\]$(parse_git_branch)\[\e[0;39m\]$ '
    export PROMPT_COMMAND='echo -ne "\033]0;${PWD}\007"'

    export INTERACTIVE_SHELL=1
else
    export INTERACTIVE_SHELL=0
fi

parse_git_branch() {
    # returns '(git branch name) ' if inside git directory,
    # otherwise returns ''
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\ (\1)/'
}

# Adds git bash completion
source ~/.git-completion.sh

# Some useful aliases
function git_current_branch() {
  git symbolic-ref HEAD 2> /dev/null | sed -e 's/refs\/heads\///'
}

function git_current_origin() {
  git config --get remote.origin.url | sed -e 's/^.*\://' | sed -e 's/\.git.*//'
}
