#!/bin/bash

# utility functions used in various scripts

# detect platform and configure platform specific settings
platform='unknown'
unamestr=$(uname)
if [[ "$unamestr" == 'Linux' ]]; then
    platform='linux'
elif [[ "$unamestr" == 'Darwin' ]]; then
    platform='darwin'
    source ~/.bash_mac_stuff
fi

