alias c='clear'
alias ls='ls -la'
alias gs='git status'
alias gb='git branch'
alias gc='git commit -m'
alias gp='git push'
alias grep="grep --color=always"
alias ..="cd .."
alias ...="cd ../.."

# for work
alias cdck="cd /data/ck/cloudkick/webapp/"

