alias c='clear'
alias ls='ls -la'
alias grep="grep --color=always"
alias ..="cd .."
alias ...="cd ../.."
alias jslint=~/dotfiles/apps/JSLintWrapper/jslint

# git
alias gpr='open "https://github.com/$(git_current_origin)/pull/new/$(git_current_branch)"'
alias gpthis='git push origin HEAD:$(git_current_branch)'
alias gs='git status -sb'
alias gb='git branch'
alias gc='git commit -m'
alias gco='git checkout'
# A better gitlog
alias gl='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)%Creset" --abbrev-commit'

##########
# for work
##########
alias cdck="cd ~/dev/reach/cloudkick/webapp/site_media"

# remove old python compiled files
alias rmpyc='find . -name "*.pyc" -delete'

# vim
alias vim='mvim -v'
